export const LOAD_MEMORY_STATZ_REQUEST = 'LOAD_MEMORY_STATZ_REQUEST';
export const LOAD_MEMORY_STATZ_SUCCESS = 'LOAD_MEMORY_STATZ_SUCCESS';
export const LOAD_MEMORY_STATZ_ERROR = 'LOAD_MEMORY_STATZ_ERROR';
