export const LOAD_SYSTEM_AVERAGE_REQUEST = 'LOAD_SYSTEM_AVERAGE_REQUEST';
export const LOAD_SYSTEM_AVERAGE_SUCCESS = 'LOAD_SYSTEM_AVERAGE_SUCCESS';
export const LOAD_SYSTEM_AVERAGE_ERROR = 'LOAD_SYSTEM_AVERAGE_ERROR';
