export const LOAD_NETWORK_STATZ_WSSTREAMING_REQUEST =
  'LOAD_NETWORK_STATZ_WSSTREAMING_REQUEST';
export const LOAD_NETWORK_STATZ_WSSTREAMING_SUCCESS =
  'LOAD_NETWORK_STATZ_WSSTREAMING_SUCCESS';
export const LOAD_NETWORK_STATZ_WSSTREAMING_ERROR =
  'LOAD_NETWORK_STATZ_WSSTREAMING_ERROR';
