export const LOAD_NETWORK_STATZ_REQUEST = 'LOAD_NETWORK_STATZ_REQUEST';
export const LOAD_NETWORK_STATZ_SUCCESS = 'LOAD_NETWORK_STATZ_SUCCESS';
export const LOAD_NETWORK_STATZ_ERROR = 'LOAD_NETWORK_STATZ_ERROR';
