export const LOAD_SYSTEM_AVERAGE_POLLING_REQUEST =
  'LOAD_SYSTEM_AVERAGE_POLLING_REQUEST';
export const LOAD_SYSTEM_AVERAGE_POLLING_SUCCESS =
  'LOAD_SYSTEM_AVERAGE_POLLING_SUCCESS';
export const LOAD_SYSTEM_AVERAGE_POLLING_ERROR =
  'LOAD_SYSTEM_AVERAGE_POLLING_ERROR';
