export const LOAD_MEMORY_STATZ_POLLING_REQUEST =
  'LOAD_MEMORY_STATZ_POLLING_REQUEST';
export const LOAD_MEMORY_STATZ_POLLING_SUCCESS =
  'LOAD_MEMORY_STATZ_POLLING_SUCCESS';
export const LOAD_MEMORY_STATZ_POLLING_ERROR =
  'LOAD_MEMORY_STATZ_POLLING_ERROR';
