export const LOAD_NETWORK_STATZ_POLLING_REQUEST =
  'LOAD_NETWORK_STATZ_POLLING_REQUEST';
export const LOAD_NETWORK_STATZ_POLLING_SUCCESS =
  'LOAD_NETWORK_STATZ_POLLING_SUCCESS';
export const LOAD_NETWORK_STATZ_POLLING_ERROR =
  'LOAD_NETWORK_STATZ_POLLING_ERROR';
