export const CHANGE_CHARTING_PERIOD = 'CHANGE_CHARTING_PERIOD';
export const CHANGE_POLLING_PERIOD = 'CHANGE_POLLING_PERIOD';
export const CHANGE_CURRENT_BREAKPOINT = 'CHANGE_CURRENT_BREAKPOINT';
export const TOGGLE_DASHBOARD_LOCK = 'TOGGLE_DASHBOARD_LOCK';
