export const LOAD_MEMORY_STATZ_WSSTREAMING_REQUEST =
  'LOAD_MEMORY_STATZ_WSSTREAMING_REQUEST';
export const LOAD_MEMORY_STATZ_WSSTREAMING_SUCCESS =
  'LOAD_MEMORY_STATZ_WSSTREAMING_SUCCESS';
export const LOAD_MEMORY_STATZ_WSSTREAMING_ERROR =
  'LOAD_MEMORY_STATZ_WSSTREAMING_ERROR';
