export const LOAD_SYSTEM_AVERAGE_WSSTREAMING_REQUEST =
  'LOAD_SYSTEM_AVERAGE_WSSTREAMING_REQUEST';
export const LOAD_SYSTEM_AVERAGE_WSSTREAMING_SUCCESS =
  'LOAD_SYSTEM_AVERAGE_WSSTREAMING_SUCCESS';
export const LOAD_SYSTEM_AVERAGE_WSSTREAMING_ERROR =
  'LOAD_SYSTEM_AVERAGE_WSSTREAMING_ERROR';
